usuarios:
  admin:
    name: Administrador
    password: $2b$12$sw2iUUFay8xhuvjKrV6KROqKWFt5wkN5Q3lO6wnjwKilRWjehfXHm
    rol: admin
    subgerencia: null
    territorio: null
  jcabalin:
    name: J. Cabalin
    password: $2b$12$nKUiBmg7z2/NLOd49liFZ.jWZ1zl0VOeRLhJs2ywBQksL8.vO7lI2
    rol: admin
    subgerencia: null
    territorio: null
  laura_sierra:
    name: Laura Sierra
    password: $2b$12$xG.X2cQqe18K5CqXBTBqs.mzCnkgOuwVSObHyfQtIxI1YZRvW31mW
    rol: jefatura
    subgerencia: SGMP0001
    territorio: SGMP0001
  terr_metro:
    name: Territorial Metropo
    password: $2b$12$TQe6xwhxulqHZMcrpTzek.nRpUwp1h7Elond4ofZTZcHR9xjKTOWq
    rol: jefatura
    subgerencia: null
    territorio: GRTR1010
  terr_norte:
    name: Territorial Norte
    password: $2b$12$vTaY8qxhkw7rx7GkkJGKzO8X2Bvwqp/BZbehdCdxCOMLJAS46ySVS
    rol: jefatura
    subgerencia: null
    territorio: GRTR1020
  terr_sur:
    name: Territorial Sur
    password: $2b$12$H5EdrP7uG6wUW.OIQ3BLBe4EF9hzoSMkYGPkkCGDohsRl6kNPnP1G
    rol: jefatura
    subgerencia: null
    territorio: GRTR1030
