cookie:
  expiry_days: 30
  key: gdd_achs_cookie_key_2026
  name: gdd_auth
credentials:
  usernames:
    Javiera Cabalin:
      email: jicabalinf@achs.cl
      name: J. Cabalin
      password: $2b$12$4JBF9rVNN1ycZLhOo2nyR.BCiBmG.ifbjvGzER7xKombnkOBxcoTW
      rol: admin
      subgerencia: null
      territorio: null
    admin:
      email: admin@achs.cl
      name: Administrador
      password: $2b$12$4gTQn2Wb7MKN0UGhggxba.PiTRo97xwAqDdm9LzSzzwDQifpylwvu
      rol: admin
      subgerencia: null
      territorio: null
    laura_sierra:
      email: lcsierras@achs.cl
      name: Laura Sierra
      password: $2b$12$5myB8/UeCZvJhbhc6tBbDeeKu0Yd8A/gGj9p6yjBJzU.OfHUFrEbq
      rol: jefatura
      subgerencia: SGMP0001
      territorio: SGMP0001
    terr_metro:
      email: rmunita@achs.cl
      name: Territorial Metropo
      password: $2b$12$Nvi7YZ2neDOOz88UZh4w/O95XpcC3ObK3Z8cl2tzlAaEcEHrhZbB.
      rol: jefatura
      subgerencia: null
      territorio: GRTR1010
    terr_norte:
      email: pariojaz@achs.cl
      name: Territorial Norte
      password: $2b$12$LET54fWur6P3odFzp/vdAObmgBEzehL9xgfPRAYmuwNRQg007rgwm
      rol: jefatura
      subgerencia: null
      territorio: GRTR1020
    terr_sur:
      email: jbaumann@achs.cl
      name: Territorial Sur
      password: $2b$12$vjwN2mOWiXMOP7bJ2qqTqehPIWrxS0LokbciuZTZPqAIH3kOcOFlS
      rol: jefatura
      subgerencia: null
      territorio: GRTR1030
pre-authorized:
  emails: []
